import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { getMenu, getShopDetails } from "@/lib/shopify";
import { MenuItem, Menus } from "@/types/menu";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import { ShopDetails } from "@/types/shopify";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuResponse: { data: Menus } = await getMenu("main-menu");
  const footerResponse: { data: Menus } = await getMenu("footer");
  
  const shopDetails: { data: ShopDetails } = await getShopDetails();

  const headerMenu = menuResponse.data.menu;
  const footerMenu = footerResponse.data.menu;
  
  const headerItems: MenuItem[] = headerMenu.items;
  const footerItems: MenuItem[] = footerMenu.items;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header menus={headerItems} shopDetails={shopDetails.data} />
        {children}
        <SpeedInsights />
        <Analytics />
        <Footer menus={footerItems} shopDetails={shopDetails.data} />
      </body>
    </html>
  );
}
